services:
  llm-convo:
    container_name: llm-convo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5234:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./templates:/app/templates
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    restart: unless-stopped
